### ISSUE TITLE
hs-source-dirs in conditional blocks?

### ISSUE THREAD

**Issue by philderbeast** [martijnbastiaan/doctest-parallel#35]
I find doctest to be picky about module paths. I'm converting a project with many packages into one package with internal libraries and gave doctest-parallel a try. Seems like loading modules from a library could save me the trouble of specifying module paths explicitly to doctest as I usually do, like this:

```haskell
module Main where

import Test.DocTest (doctest)

arguments :: [String]
arguments =
    [ "src-NoStandaloneKindSignatures/Data/Theory/UoM.hs"
    , "src/Data/UnitsOfMeasure/Unsafe/NormalForm.hs"
    , "src/Data/UnitsOfMeasure/Unsafe/Quantity.hs"
    , "src/Data/UnitsOfMeasure/Read.hs"
    , "src/Data/UnitsOfMeasure/Show.hs"
    , "src/Data/UnitsOfMeasure/Singleton.hs"
    , "src-NoStandaloneKindSignatures/Data/UnitsOfMeasure/Syntax.hs"
    ]

main :: IO ()
main = doctest arguments
```

So far with doctest-parallel, I find that `extractSpecificCabalLibrary` is not picking up all of the library source dirs, skipping those in cabal conditional blocks.

```haskell
module Main where

import Debug.Trace
import Test.DocTest
import Test.DocTest.Helpers
import System.Environment (getArgs)

main :: IO ()
main = do
    pkg <- findCabalPackage "plugins-for-blobs"
    lib <- traceShowId <$> extractSpecificCabalLibrary (Just "uom-quantity") pkg
    mainFromLibrary lib =<< getArgs
```

```cabal
-- plugins-for-blobs.cabal
library uom-quantity
  exposed-modules:
      Data.Theory.UoM
      ...
  hs-source-dirs:
      uom-quantity/src
  if impl(ghc >= 8.2.0) && impl(ghc < 8.4.0)
    hs-source-dirs:
        uom-quantity/src-ghc-8.2
        uom-quantity/src-NoStandaloneKindSignatures
```

The trace is showing that only `uom-quantity/src` is being picked up.

```
Library
    { libSourceDirectories = ["/.../plugins-for-blobs/uom-quantity/src"]
    , libCSourceDirectories = []
    , libModules = [...]
    , libDefaultExtensions = []
    }
```

**Comment by martijnbastiaan** [comment]
Thanks for the report!

Conditionals aren't resolved yet. I'll see if I can find the right functions in Cabal-the-library to resolve them; hopefully this weekend.

**Comment by philderbeast** [comment]
Even though I've contributed to Cabal before, digging around there's a lot to sift through. For the meantime I've opted to go with this workaround, enabling me to test with `doctest-parallel` for ghc-9.2.2.

```haskell
module Main where

import Test.DocTest
import Test.DocTest.Helpers
import Test.DocTest.Internal.Interpreter (ghcInfo)
import System.Environment (getArgs)

dirs922 :: [FilePath]
dirs922 =
    [ "./uom-quantity/src"
    , "./uom-quantity/src-ghc-9.0"
    , "./uom-quantity/src-StandaloneKindSignatures"
    ]

main :: IO ()
main = do
    pkg <- findCabalPackage "plugins-for-blobs"
    lib <- extractSpecificCabalLibrary (Just "uom-quantity") pkg

    info <- filter ((== "Project version") . fst) <$> ghcInfo
    case info of
        [("Project version", "9.2.2")] -> do
            getArgs >>= mainFromLibrary lib { libSourceDirectories = dirs922 }
        [("Project version", v)] -> error $ "Not performing doctest with-compiler: ghc-" <> v
        _ -> error "Could not find GHC interpreter version"
```

**Comment by philderbeast** [comment]
The experience of moving from `doctest` to `doctest-parallel` was great. I had to export more things. Only hit one glitch with this test:

```
-- | Extract the underlying value of a quantity
--
-- >>> unQuantity (1 :: Quantity Double Data.Theory.UoM.One)
-- 1.0
unQuantity :: Quantity a u -> a
unQuantity (MkQuantity x) = x
```

Got it working by fully qualifying `Data.Theory.UoM.One`.

```haskell
module Data.Theory.UoM where

-- | Dimensionless unit (identity element)
type One :: Unit
type family One where {}
```

For the test, I couldn't use the following setup to use `One` unqualified:

```
-- $setup
-- >>> import Data.Theory.UoM
```

Here's the error:

```
/.../plugins-for-blobs/uom-quantity/src/Data/UnitsOfMeasure/Unsafe/Quantity.hs:80:
  failure in expression `unQuantity (1 :: Quantity Double One)'
expected: 1.0
 but got:
          ^
          <interactive>:27:34: error:
              Not in scope: type constructor or class ‘One’

Examples: 83  Tried: 83  Errors: 0  Unexpected output: 1
```

I'm really liking `doctest-parallel` so far.

**Comment by martijnbastiaan** [comment]
@philderbeast Would you mind testing https://github.com/martijnbastiaan/doctest-parallel/pull/37?

> Only hit one glitch with this test:

That's a weird glitch. I'll investigate (probably next weekend :-)).

**Comment by philderbeast** [comment]
Thanks @martijnbastiaan, I'm on it.

Which compiler version are you working with? I see `Flags` was separated from `ConfVar` 3 years ago.

https://github.com/haskell/cabal/blame/0abbe37187f708e0a5daac8d388167f72ca0db7e/Cabal-syntax/src/Distribution/Types/ConfVar.hs

**Comment by philderbeast** [comment]
That seems to be working with `ghc-9.2.2` after working around the `Flag _` pattern match compile error. The included source directories look good to me.

```
{ libSourceDirectories =
  ["/.../plugins-for-blobs/uom-quantity/src"
  ,"/.../plugins-for-blobs/uom-quantity/src-ghc-9.0"
  ,"/.../plugins-for-blobs/uom-quantity/src-StandaloneKindSignatures"
  ]
, ...
}
```

The updated test-suite main module:

```haskell
module Main where

import Debug.Trace
import Test.DocTest
import Test.DocTest.Helpers
import System.Environment (getArgs)

main :: IO ()
main = do
    pkg <- findCabalPackage "plugins-for-blobs"
    lib <- extractSpecificCabalLibrary (Just "uom-quantity") pkg
    getArgs >>= mainFromLibrary (traceShowId lib)
```

**Comment by martijnbastiaan** [comment]
Ah I see, should have waited for CI 🙈. Thanks for confirming!

**Comment by philderbeast** [comment]
@martijnbastiaan I made a small pull request to the `fix-35` branch.

**Comment by martijnbastiaan** [comment]
Wow thanks, let's see what CI says!

**Comment by philderbeast** [comment]
Sorry to say but I only tested with cabal install, not with stack.

**Comment by philderbeast** [comment]
All the cabal CI tests passed. Added another commit to that PR for the stack failures. That CI job is pending awaiting your approval.

**Comment by martijnbastiaan** [comment]
The PR looks good now IMO. Any comments before I merge?

**Comment by martijnbastiaan** [comment]
@philderbeast The fix is part of `doctest-parallel-0.2.3` now!

**Comment by philderbeast** [comment]
Great stuff, thanks @martijnbastiaan.

Trying it now where I have cabal conditonals and the doctests build with no ambiguous modules reported.
